version: '3.1'
services:
  nginx:
    image: registry.gitlab.com/chonlatee/html-template
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./dist/:/usr/share/nginx/html